version: "3"
services:
  server:
    build:
      context: src
    ports:
      - "5002:5000"
    environment:
      "ACCESSKEYID": ""
      "ACCESSSECRET": ""

    container_name: "aliddns-http-server"